### ISSUE TITLE
Add six.moves.collections.abc

### ISSUE THREAD

**Issue by benjaminp** [benjaminp/six#155] opened 2016-05-29 17:31 UTC
Originally reported by: **Eklavya Sharma (Bitbucket: [ekujupr](https://bitbucket.org/ekujupr), GitHub: Unknown)**

----------------------------------------

I'm fed up of doing

```py
try:
    import collections.abc as collections_abc # only works on python 3.3+
except ImportError:
    import collections as collections_abc
```

A `six.moves.collections.abc` would be very convenient.

----------------------------------------
- Bitbucket: https://bitbucket.org/gutworth/six/issue/155

**Comment by WildCard65** [comment] 2018-01-31 14:47
Bumping this issue as Python 3.7 (once it release) may end up giving a deprecation warning for using classes from collections.abc in collections itself.

Reference: https://github.com/python/cpython/pull/5460

**Comment by haikuginger** [comment] 2018-02-02 13:52
I'm 👍 on this request. With the removal of the `collections.abc` items from `collections` in Python 3.8, now is the right time to do this so we can transition appropriately.

Reference: shazow/urllib3#1324

**Comment by NeilGirdhar** [comment] 2019-05-31 18:17
Duplicate of https://github.com/benjaminp/six/pull/241

**Comment by nickwilliams-eventbrite** [comment] 2019-05-31 18:23
> Duplicate of #241

This is not correct. This is an issue. #241 is a pull request. In fact, #241's comment specifically says that it resolves #155 (this). So ... this is not a duplicate. It's the companion issue to the #241 pull request.

**Comment by WildCard65** [comment] 2019-05-31 18:29
To add onto what @nickwilliams-eventbrite said, should #241 get accepted, GitHub will automatically close this issue as the PR's comment has "closes <issue number>" in it.

**Comment by NeilGirdhar** [comment] 2019-05-31 18:46
oh right, sorry, was quickly searching for #241, and ran into this in the search.

**Comment by NeilGirdhar** [comment] 2019-05-31 18:48
Although, it is confusing that most of the discussion there is about whether this should be done at all (that discussion should be here, I think).

**Closed** 2019-11-05 07:21 UTC
Labels: minor, proposal
